src/Entity/Messages.php
<?php

namespace App\Entity;

use App\Repository\MessagesRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MessagesRepository::class)
 */
class Messages
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $message;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_read = 0;

    /**
     * @ORM\ManyToOne(targetEntity=Freelancer::class, inversedBy="sent")
     * @ORM\JoinColumn(nullable=false)
     */
    private $sender;

    /**
     * @ORM\ManyToOne(targetEntity=Freelancer::class, inversedBy="received")
     * @ORM\JoinColumn(nullable=false)
     */
    private $recipient;

    public function __construct()
    {
        $this->created_at = new \DateTime();
    }
    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTime $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getIsRead(): ?bool
    {
        return $this->is_read;
    }

    public function setIsRead(bool $is_read): self
    {
        $this->is_read = $is_read;

        return $this;
    }

    public function getSender(): ?Freelancer
    {
        return $this->sender;
    }

    public function setSender(?Freelancer $sender): self
    {
        $this->sender = $sender;

        return $this;
    }

    public function getRecipient(): ?Freelancer
    {
        return $this->recipient;
    }

    public function setRecipient(?Freelancer $recipient): self
    {
        $this->recipient = $recipient;

        return $this;
    }
}

src/Form/MessagesType.php
<?php

namespace App\Form;

use App\Entity\Freelancer;
use App\Entity\Messages;
// use Doctrine\DBAL\Types\TextType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MessagesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, [
                "attr" => [
                    "class" => "form-control"
                ]
            ])
            ->add('message', TextareaType::class,[
                "attr" => [
                    "class" => "form-control"
                ]
            ])
            ->add('recipient', EntityType::class, [
                "class"=>Freelancer::class, 
                "choice_label" => "email", 
                "attr" => [
                    "class"=>"form-control"
                ]
            ])

            ->add('envoyer', SubmitType::class, [
                "attr"=> [
                    "class" => "btn btn-success"
            ]
            
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Messages::class,
        ]);
    }
}

src/Controller/MessagesController.php
<?php

namespace App\Controller;

use App\Entity\Messages;
use App\Form\MessagesType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MessagesController extends AbstractController
{
    /**
     * @Route("/messages", name="messages")
     */
    public function index(): Response
    {
        return $this->render('messages/index.html.twig', [
            'controller_name' => 'MessagesController',
        ]);
    }

    /**
     * @Route("/send", name="send")
     */
    public function send(Request $request): Response
    {
        $message = new Messages;
        $form = $this->createForm(MessagesType::class, $message);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $message->setSender($this->getUser());

            $em = $this->getDoctrine()->getManager();
            $em->persist($message);
            $em->flush();

            $this->addFlash("message", "Message envoyé avec succès.");
            return $this->redirectToRoute("messages");
        }

        return $this->render("messages/send.html.twig", [
            "form" => $form->createView()
        ]);
    }

    /**
     * @Route("/received", name="received")
     */
    public function received(): Response
    {
        return $this->render('messages/received.html.twig');
    }

    /**
     * @Route("/sent", name="sent")
     */
    public function sent(): Response
    {
        return $this->render('messages/sent.html.twig');
    }

    /**
     * @Route("/read/{id}", name="read")
     */
    public function read(Messages $message): Response
    {
        $message->setIsRead(true);
        $em = $this->getDoctrine()->getManager();
        $em->persist($message);
        $em->flush();
        return $this->render('messages/read.html.twig', compact("message"));
    }

    /**
     * @Route("/delete/{id}", name="delete")
     */
    public function delete(Messages $message): Response
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($message);
        $em->flush();

        return $this->redirectToRoute("received");
    }
}

templates/messages/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messaging
{% endblock %}

{% block body %}
	<section class="container">
		<div class="row">
			<div class="col">
				<h1>MyMailBox</h1>
				<br>
				<h2>What's up ?</h2>
				<br>
				<h4>Recieved:{{ app.user.received|length }}</h4>
				<h4>Sent:{{ app.user.sent|length }}</h4>
				<a class="btn btn-success" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
					Show my folders
				</a>
				<a href="{{path("send")}}" class="btn btn-success">Send a message</a>
			</div>
		</div>
	</section>
	<br><br><br><br><br><br><br><br><br>
	<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
		<div class="offcanvas-header">
			<h2 class="offcanvas-title" id="offcanvasExampleLabel">Folders</h2>
			<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
		</div>
		<div class="offcanvas-body">
			<div class="list-group">
				<a href="{{ path("messages") }}" class="list-group-item list-group-item-action active">Home</a>
			</div>
			<div class="list-group">
				<a href="{{ path("received") }}" class="list-group-item list-group-item-action ">Inbox</a>
			</div>
			<div class="list-group">
				<a href="{{ path("sent") }}" class="list-group-item list-group-item-action ">Sent Messages</a>
			</div>
		</div>
	</div>
{% endblock %}

templates/messages/read.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messagerie{% endblock %}

{% block body %}
	<section class="container">
		<div class="row">
			<div class="col-12">
				<h1>MyMailBox</h1>
				<br>
                <h2>Sender: {{ message.sender.email }}</h2>
                <h4>Object :{{ message.title }}</h4>
                <h4>Date: {{ message.createdAt|date }}</h4>
                <h4>Message:</h4>
				<br>
                <p>{{ message.message }}</p>
				<a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
					See my folders
				</a>
                <a href="{{path("received")}}" class="btn btn-primary">Back to the Mailbox</a>
			</div>
		</div>
	</section>
	<br><br><br><br><br><br><br><br><br>
	<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
		<div class="offcanvas-header">
			<h2 class="offcanvas-title" id="offcanvasExampleLabel">My folders</h2>
			<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
		</div>
		<div class="offcanvas-body">
            <div class="list-group">
                <a href="{{ path("messages") }}" class="list-group-item list-group-item-action">Home</a>
            </div>
            <div class="list-group">
                <a href="{{ path("received") }}" class="list-group-item list-group-item-action active">MailBox</a>
            </div>
            <div class="list-group">
                <a href="{{ path("messages") }}" class="list-group-item list-group-item-action">Sent messages</a>
            </div>
		</div>
	</div>
{% endblock %}

templates/messages/received.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messaging{% endblock %}

{% block body %}
	<section class="container">
		<div class="row">
			<div class="col-12">
				<h1>MyMailBox</h1>
				<br>
				<h2>Messages received:</h2>
				<h4>You have received {{ app.user.received|length }} messages</h4>
				<br>
            </div>
				<div class="col-3 fw-bold">From</div>
				<div class="col-3 fw-bold">About</div>
				<div class="col-3 fw-bold">Date</div>
				<div class="col-3 fw-bold">Actions</div>
            	{% for message in app.user.received %}
					{% set bold = "" %}
					{% if message.isRead == 0 %}
						{% set bold = "fw-bold" %}
					{% endif %}


				<div class="col-3 {{bold}}">{{ message.sender.email }}</div>
				<div class="col-3 {{bold}}">
					<a href="{{ path("read", {id: message.id}) }}">{{ message.title }}</a>
				</div>
				<div class="col-3 {{bold}}">{{ message.createdAt|date }}</div>
				<div class="col-3">
                    <a href="{{ path("delete", {id: message.id}) }}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-excel-fill text-danger" viewbox="0 0 16 16">
                            <path d="M12 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zM5.884 4.68L8 7.219l2.116-2.54a.5.5 0 1 1 .768.641L8.651 8l2.233 2.68a.5.5 0 0 1-.768.64L8 8.781l-2.116 2.54a.5.5 0 0 1-.768-.641L7.349 8 5.116 5.32a.5.5 0 1 1 .768-.64z"/>
                        </svg>
                    </a>
				</div>
			{% endfor %}

            <div class="col">
				<a class="btn btn-success" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
					Show my folders
				</a>
                <a href="{{path("send")}}" class="btn btn-success">Send a message</a>
			</div>
		</div>
	</section>
	<br><br><br><br><br><br><br><br><br>
	<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
		<div class="offcanvas-header">
			<h2 class="offcanvas-title" id="offcanvasExampleLabel">Folders</h2>
			<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
		</div>
		<div class="offcanvas-body">
			<div class="list-group">
				<a href="{{ path("messages") }}" class="list-group-item list-group-item-action">Home</a>
			</div>
			<div class="list-group">
				<a href="{{ path("received") }}" class="list-group-item list-group-item-action active">Inbox</a>
			</div>
			<div class="list-group">
				<a href="{{ path("sent") }}" class="list-group-item list-group-item-action ">Sent Messages</a>
			</div>
		</div>
	</div>
{% endblock %}

templates/messages/send.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messaging{% endblock %}

{% block body %}
	<section class="container">
		<div class="row">
			<div class="col">
				<h1>Send a message</h1>
				<br>
				{{ form(form) }}
				<a class="btn btn-success" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
					Show my folders
				</a>
			</div>
		</div>
	</section>
	<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
		<div class="offcanvas-header">
			<h2 class="offcanvas-title" id="offcanvasExampleLabel">Folders</h2>
			<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
		</div>
		<div class="offcanvas-body">
			<div class="list-group">
				<a href="{{ path("messages") }}" class="list-group-item list-group-item-action ">Home</a>
			</div>
			<div class="list-group">
				<a href="{{ path("messages") }}" class="list-group-item list-group-item-action ">Inbox</a>
			</div>
			<div class="list-group">
				<a href="{{ path("messages") }}" class="list-group-item list-group-item-action ">Sent Messages</a>
			</div>
		</div>
	</div>
{% endblock %}

templates/messages/sent.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messagerie
{% endblock %}

{% block body %}
	<section class="container">
		<div class="row">
			<div class="col-12">
				<h1>MyMailBox</h1>
				<br>
				<h2>Messages sent:</h2>
				<h4>You have sent {{ app.user.sent|length }} messages</h4>
				<br>
			</div>
			<div class="col-3 fw-bold">from</div>
			<div class="col-3 fw-bold">About</div>
			<div class="col-3 fw-bold">Date</div>
			<div class="col-3 fw-bold">Actions</div>
			{% for message in app.user.sent %}
				{% set bold = "" %}
				{% if message.isRead == 0 %}
					{% set bold = "fw-bold" %}
				{% endif %}

				<div class="col-3 {{bold}}">{{ message.sender.email }}</div>
				<div class="col-3 {{bold}}">
					<a href="{{ path("read", {id: message.id}) }}">{{ message.title }}</a>
				</div>
				<div class="col-3 {{bold}}">{{ message.createdAt|date }}</div>
				<div class="col-3">
                    <a href="{{ path("delete", {id: message.id}) }}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-excel-fill text-danger" viewbox="0 0 16 16">
                            <path d="M12 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2zM5.884 4.68L8 7.219l2.116-2.54a.5.5 0 1 1 .768.641L8.651 8l2.233 2.68a.5.5 0 0 1-.768.64L8 8.781l-2.116 2.54a.5.5 0 0 1-.768-.641L7.349 8 5.116 5.32a.5.5 0 1 1 .768-.64z"/>
                        </svg>
                    </a>
				</div>
			{% endfor %}


			<div class="col">
				<a class="btn btn-success" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
					Show my folders
				</a>
				<a href="{{path("send")}}" class="btn btn-success">Send a message</a>
			</div>
		</div>
	</section>
	<br><br><br><br><br><br><br><br><br>
	<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
		<div class="offcanvas-header">
			<h2 class="offcanvas-title" id="offcanvasExampleLabel">My folders</h2>
			<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
		</div>
		<div class="offcanvas-body">
			<div class="list-group">
				<a href="{{ path("messages") }}" class="list-group-item list-group-item-action">Home</a>
			</div>
			<div class="list-group">
				<a href="{{ path("received") }}" class="list-group-item list-group-item-action">MailBox</a>
			</div>
			<div class="list-group">
				<a href="{{ path("sent") }}" class="list-group-item list-group-item-action active">Sent Messages</a>
			</div>
		</div>
	</div>
{% endblock %}